// Standard service parts commonly used during extinguisher servicing
export const STANDARD_SERVICE_PARTS = [
  {
    id: 'oring',
    name: 'O-Ring',
    description: 'Replacement O-ring seal',
    defaultPrice: 2.50,
    category: 'Seals',
  },
  {
    id: 'safety-pin',
    name: 'Safety Pin',
    description: 'Replacement safety pin with tag',
    defaultPrice: 1.50,
    category: 'Safety',
  },
  {
    id: 'tamper-seal',
    name: 'Tamper Seal',
    description: 'Anti-tamper seal ring',
    defaultPrice: 0.75,
    category: 'Safety',
  },
  {
    id: 'pressure-gauge',
    name: 'Pressure Gauge',
    description: 'Replacement pressure gauge',
    defaultPrice: 12.00,
    category: 'Gauges',
  },
  {
    id: 'discharge-hose',
    name: 'Discharge Hose',
    description: 'Replacement discharge hose assembly',
    defaultPrice: 18.50,
    category: 'Hoses',
  },
  {
    id: 'wall-bracket',
    name: 'Wall Bracket',
    description: 'Standard wall mounting bracket',
    defaultPrice: 8.00,
    category: 'Mounting',
  },
  {
    id: 'service-label',
    name: 'Service Label',
    description: 'Annual service inspection label',
    defaultPrice: 0.50,
    category: 'Labels',
  },
  {
    id: 'discharge-nozzle',
    name: 'Discharge Nozzle',
    description: 'Replacement nozzle/horn',
    defaultPrice: 15.00,
    category: 'Nozzles',
  },
  {
    id: 'valve-assembly',
    name: 'Valve Assembly',
    description: 'Complete valve head assembly',
    defaultPrice: 45.00,
    category: 'Valves',
  },
  {
    id: 'dip-tube',
    name: 'Dip Tube',
    description: 'Internal siphon/dip tube',
    defaultPrice: 8.50,
    category: 'Internal',
  },
  {
    id: 'annual-service',
    name: 'Annual Service',
    description: 'Standard annual service labour',
    defaultPrice: 15.00,
    category: 'Labour',
    isLabour: true,
  },
  {
    id: 'extended-service',
    name: 'Extended Service',
    description: '5-year extended service with discharge test',
    defaultPrice: 35.00,
    category: 'Labour',
    isLabour: true,
  },
  {
    id: 'recharge',
    name: 'Recharge',
    description: 'Recharge with extinguishing agent',
    defaultPrice: 25.00,
    category: 'Labour',
    isLabour: true,
  },
];

export type StandardServicePart = typeof STANDARD_SERVICE_PARTS[number];
